# Generated by Django 5.1 on 2024-08-08 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_course_course_picture_student_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='student',
            name='mode_of_study',
            field=models.CharField(choices=[('virtual', 'Virtual(Online)'), ('physical', 'Physical')], default='physical', max_length=15),
        ),
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course', to='school.course'),
        ),
    ]
