# Generated by Django 5.1 on 2024-08-08 05:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IdealPrintshop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='printshopservice',
            name='product_picture',
            field=models.ImageField(blank=True, null=True, upload_to='service_pictures/'),
        ),
        migrations.AddField(
            model_name='printshopservice',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='IdealPrintshop.category'),
        ),
    ]
