# Generated by Django 5.1 on 2024-08-08 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_student_is_active_student_mode_of_study_and_more'),
        ('staff', '0002_printshopoperator_profile_picture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='printshopoperator',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='subject',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='school.course'),
        ),
    ]
